/**
 * Created by nick on 2018/6/28.
 */
export default {
    "route_name" : {
        "Login" : "Login",
        "My" : "My",
        "Register" : "Register",
        "BaseInfo" : "BaseInfo",
        "Bill" : "Bill",
        "BillAdd" : "BillAdd",
        "BillAddAddProduct" : "BillAddAddProduct",
        "BillDetail" : "BillDetail",
        "Provider" : "Provider",
        "ProviderAdd" : "ProviderAdd",
        "ProviderDetail" : "ProviderDetail",
        "Customer" : "Customer",
        "CustomerAdd" : "CustomerAdd",
        "CustomerDetail" : "CustomerDetail",
        "Product" : "Product",
        "ProductAdd" : "ProductAdd",
        "ProductDetail" : "ProductDetail",
        "ProductBatch" : "ProductBatch",
        "ProductBatchAdd" : "ProductBatchAdd",
        "ProductBatchDetail" : "ProductBatchDetail",
    },

    /**
     *
     * icon_font
     * http://www.iconfont.cn/collections/detail?cid=4491
     */
    "icon_font_name" : {
        "enter" : "enter",
        "return" : "return",
        "packup" : "packup",
        "unfold" : "unfold",
        "add" : "add",
        "switch" : "switch",
        "setup" : "setup",
        "right" : "right",
        "refresh" : "refresh",
        "prompt" : "prompt",
        "picture" : "picture",
        "people" : "people",
        "other" : "other",
        "order" : "order",
        "more" : "more",
        "mine" : "mine",
        "message" : "message",
        "manage" : "manage",
        "like" : "like",
        "like_fill" : "like_fill",
        "homepage" : "homepage",
        "label" : "label",
        "headlines" : "headlines",
        "flashlight" : "flashlight",
        "flag" : "flag",
        "feedback" : "feedback",
        "enterinto" : "enterinto",
        "empty" : "empty",
        "emoji" : "emoji",
        "eit" : "eit",
        "editor" : "editor",
        "dynamic" : "dynamic",
        "document" : "document",
        "delete" : "delete",
        "createtask" : "createtask",
        "coordinates" : "coordinates",
        "collection" : "collection",
        "collection_fill" : "collection_fill",
        "close" : "close",
        "clock" : "clock",
        "camera" : "camera",
        "businesscard" : "businesscard",
        "addressbook" : "addressbook",
        "addpeople" : "addpeople",
        "addition" : "addition",
        "activity" : "activity",

    },
};